export default players = [
    "Giannis Antetokounmpo",
    "De'Aaron Fox",
    "Damian Lillard",
    "Julius Randle",
    "Jayson Tatum",
    "Domantas Sabonis",
    "Ja Morant",
    "Donovan Mitchell",
    "Steph Curry",
    "Jaren Jackson",
    "Joel Embid",
    "Lebron James",
    "Luka Doncic",
    "Nikola Jokic",
    "Tyrese Haliburton",
    "Bam Adebayo",
    "DeMar DeRozan",
    "Jrue Holiday",
    "Jaylen Brown",
    "Anthony Edwards",
    "Lauri Markkanen",
    "Shai Gilgeous-Alexander"
]